# 수업에 사용될 라이브러리 설치

In [2]:
!dir   # 윈도우 사용자의 경우 -> dir 

������ ã�� �� �����ϴ�.


In [1]:
!pip install -r requirements.txt

^C
  Using cached cycler-0.10.0-py2.py3-none-any.whl (6.5 kB)
  Using cached requests-2.26.0-py2.py3-none-any.whl (62 kB)
  Attempting uninstall: numpy
    Found existing installation: numpy 1.21.2
    Uninstalling numpy-1.21.2:
      Successfully uninstalled numpy-1.21.2


ERROR: Could not install packages due to an OSError: [WinError 5] 액세스가 거부되었습니다: 'c:\\users\\testworks\\appdata\\local\\programs\\python\\python37\\lib\\site-packages\\~umpy\\.libs\\libopenblas.XWYDX2IKJW2NMTWSFYNGFUWKQU3LYTCZ.gfortran-win_amd64.dll'
Consider using the `--user` option or check the permissions.

You should consider upgrading via the 'c:\users\testworks\appdata\local\programs\python\python37\python.exe -m pip install --upgrade pip' command.


# Numpy 소개

In [3]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

In [4]:
import numpy as np

In [5]:
np.__version__

'1.17.0'

## ndarray dtype

In [6]:
a = np.array([1, 2, 3])
a

array([1, 2, 3])

In [7]:
type(a)

numpy.ndarray

In [8]:
# indexing이 list와 방식이 같음
a[0]

1

In [9]:
a.

SyntaxError: invalid syntax (Temp/ipykernel_27560/3905452595.py, line 1)

- append() 같은 함수가 없음 -> 즉, python의 list와는 다른 data type임

## Universal function

In [11]:
a = [1, 2, 3]
b = [4, 5, 6]

new_list = []
for e1, e2 in zip(a, b):
    new_list.append(e1 + e2)
new_list

[5, 7, 9]

In [12]:
a + b

[1, 2, 3, 4, 5, 6]

In [13]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

In [14]:
# 길이가 길어도 근사적으로 1초가 걸린다
a + b

array([5, 7, 9])

In [15]:
# np.sum
# np.abs
# np.log
# np.exp
# np.isnan
# ...

- n차원 array

In [16]:
a = np.array([  [1, 2],  [3, 4]   ])
a

array([[1, 2],
       [3, 4]])

In [18]:
# readability 높이기
a = np.array(
    [
        [1, 2],
        [3, 4],
    ]
)
a

array([[1, 2],
       [3, 4]])

In [19]:
a[0][1]

2

In [20]:
a + a

array([[2, 4],
       [6, 8]])