# 수업에 사용될 라이브러리 설치

In [1]:
!dir   # 윈도우 사용자의 경우 -> dir 

파일을 찾을 수 없습니다.


In [2]:
!pip install -r requirements.txt

  Using cached pandas-0.25.1-cp38-cp38-win_amd64.whl
  Using cached numpy-1.17.0.zip (6.5 MB)
  Using cached seaborn-0.9.0-py3-none-any.whl (208 kB)

  ERROR: Command errored out with exit status 1:
   command: 'C:\Users\USER\anaconda3\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\USER\\AppData\\Local\\Temp\\pip-install-39zd32st\\numpy_65a33d1f18664d2bb70e6eed76b791eb\\setup.py'"'"'; __file__='"'"'C:\\Users\\USER\\AppData\\Local\\Temp\\pip-install-39zd32st\\numpy_65a33d1f18664d2bb70e6eed76b791eb\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\USER\AppData\Local\Temp\pip-wheel-j5clqfjq'
       cwd: C:\Users\USER\AppData\Local\Temp\pip-install-39zd32st\numpy_65a33d1f18664d2bb70e6eed76b791eb\
  Complete output (2011 lines):
  Running from numpy source directory.
  blas_opt_info:
  blas_mkl_info:
  No module named 'numpy.distutils._msvccompiler' 


  Using cached matplotlib-3.1.1.tar.gz (37.8 MB)
  Using cached finance_datareader-0.9.1-py3-none-any.whl (17 kB)

    libraries mkl_rt not found in ['C:\\Users\\USER\\anaconda3\\lib', 'C:\\', 'C:\\Users\\USER\\anaconda3\\libs']
    NOT AVAILABLE
  
  blis_info:
  No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
  customize MSVCCompiler
    libraries blis not found in ['C:\\Users\\USER\\anaconda3\\lib', 'C:\\', 'C:\\Users\\USER\\anaconda3\\libs']
    NOT AVAILABLE
  
  openblas_info:
  No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
  customize MSVCCompiler
  No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
  customize MSVCCompiler
    libraries openblas not found in ['C:\\Users\\USER\\anaconda3\\lib', 'C:\\', 'C:\\Users\\USER\\anaconda3\\libs']
  get_default_fcompiler: matching types: '['gnu', 'intelv', 'absoft', 'compaqv', 'intelev', 'gnu95', 'g95', 'intelvem', 'intelem', 'flang']'

# Numpy 소개

In [3]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"


  Running setup.py clean for numpy
  Running setup.py clean for matplotlib
Failed to build numpy matplotlib
  Attempting uninstall: numpy
    Found existing installation: numpy 1.19.2
    Uninstalling numpy-1.19.2:
      Successfully uninstalled numpy-1.19.2
    Running setup.py install for numpy: started
    Running setup.py install for numpy: finished with status 'error'
  Rolling back uninstall of numpy
  Moving to c:\users\user\anaconda3\lib\site-packages\numpy-1.19.2.dist-info\
   from C:\Users\USER\anaconda3\Lib\site-packages\~umpy-1.19.2.dist-info
  Moving to c:\users\user\anaconda3\lib\site-packages\numpy\
   from C:\Users\USER\anaconda3\Lib\site-packages\~umpy
  Moving to c:\users\user\anaconda3\scripts\f2py-script.py
   from C:\Users\USER\AppData\Local\Temp\pip-uninstall-ga76h35x\f2py-script.py
  Moving to c:\users\user\anaconda3\scripts\f2py.exe
   from C:\Users\USER\AppData\Local\Temp\pip-uninstall-ga76h35x\f2py.exe



  customize GnuFCompiler
  Could not locate executable g77
  Could not locate executable f77
  customize IntelVisualFCompiler
  Could not locate executable ifort
  Could not locate executable ifl
  customize AbsoftFCompiler
  Could not locate executable f90
  customize CompaqVisualFCompiler
  Could not locate executable DF
  customize IntelItaniumVisualFCompiler
  Could not locate executable efl
  customize Gnu95FCompiler
  Could not locate executable gfortran
  Could not locate executable f95
  customize G95FCompiler
  Could not locate executable g95
  customize IntelEM64VisualFCompiler
  customize IntelEM64TFCompiler
  Could not locate executable efort
  Could not locate executable efc
  customize PGroupFlangCompiler
  Could not locate executable flang
  don't know how to compile Fortran code on platform 'nt'
    NOT AVAILABLE
  
  atlas_3_10_blas_threads_info:
  Setting PTATLAS=ATLAS
  No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
  custo

In [4]:
import numpy as np


  No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
  customize MSVCCompiler
    libraries tatlas,tatlas not found in C:\
  No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
  customize MSVCCompiler
    libraries lapack_atlas not found in C:\Users\USER\anaconda3\libs
  No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
  customize MSVCCompiler
    libraries tatlas,tatlas not found in C:\Users\USER\anaconda3\libs
  <class 'numpy.distutils.system_info.atlas_3_10_threads_info'>
    NOT AVAILABLE
  
  atlas_3_10_info:
  No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
  customize MSVCCompiler
    libraries lapack_atlas not found in C:\Users\USER\anaconda3\lib
  No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
  customize MSVCCompiler
    libraries satlas,satlas not found in C:\Users\USER\ana

  C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29333\bin\HostX86\x64\link.exe /nologo /INCREMENTAL:NO /LTCG /MANIFEST:EMBED,ID=1 /LIBPATH:C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29333\ATLMFC\lib\x64 /LIBPATH:C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29333\lib\x64 /LIBPATH:C:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\lib\um\x64 /LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.18362.0\ucrt\x64 /LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.18362.0\um\x64 _configtest.obj /OUT:_configtest.exe
  success!
  removing: _configtest.c _configtest.obj _configtest.obj.d _configtest.exe
  C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29333\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -Inumpy\core\src\common -Inumpy\core\src -Inumpy\core -Inumpy\core\src\npymath -Inumpy\core\src\multiarray -Inumpy\core\src\umath

  C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29333\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -Inumpy\core\src\common -Inumpy\core\src -Inumpy\core -Inumpy\core\src\npymath -Inumpy\core\src\multiarray -Inumpy\core\src\umath -Inumpy\core\src\npysort -IC:\Users\USER\anaconda3\include -IC:\Users\USER\anaconda3\include -IC:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29333\ATLMFC\include -IC:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29333\include -IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\include\um -IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\ucrt -IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\shared -IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um -IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\winrt -IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\cppwinrt /Tc_configtest.c /Fo_co

  failure.
  removing: _configtest.c _configtest.obj _configtest.obj.d
  C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29333\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -Inumpy\core\src\common -Inumpy\core\src -Inumpy\core -Inumpy\core\src\npymath -Inumpy\core\src\multiarray -Inumpy\core\src\umath -Inumpy\core\src\npysort -IC:\Users\USER\anaconda3\include -IC:\Users\USER\anaconda3\include -IC:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29333\ATLMFC\include -IC:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29333\include -IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\include\um -IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\ucrt -IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\shared -IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um -IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\winrt -IC:\Program Files (x86

  creating build\src.win-amd64-3.8\numpy\core\src\umath
  conv_template:> build\src.win-amd64-3.8\numpy\core\src\umath\funcs.inc
    adding 'build\src.win-amd64-3.8\numpy\core\src\umath' to include_dirs.
  conv_template:> build\src.win-amd64-3.8\numpy\core\src\umath\simd.inc
  conv_template:> build\src.win-amd64-3.8\numpy\core\src\umath\loops.h
  conv_template:> build\src.win-amd64-3.8\numpy\core\src\umath\loops.c
  conv_template:> build\src.win-amd64-3.8\numpy\core\src\umath\matmul.h
  conv_template:> build\src.win-amd64-3.8\numpy\core\src\umath\matmul.c
  conv_template:> build\src.win-amd64-3.8\numpy\core\src\umath\clip.h
  conv_template:> build\src.win-amd64-3.8\numpy\core\src\umath\clip.c
  conv_template:> build\src.win-amd64-3.8\numpy\core\src\umath\scalarmath.c
    adding 'build\src.win-amd64-3.8\numpy\core\src\npymath' to include_dirs.
  conv_template:> build\src.win-amd64-3.8\numpy\core\src\common\templ_common.h
    adding 'build\src.win-amd64-3.8\numpy\core\src\common' to incl

  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib.win-amd64-3.8
  copying lib\pylab.py -> build\lib.win-amd64-3.8
  creating build\lib.win-amd64-3.8\matplotlib
  copying lib\matplotlib\afm.py -> build\lib.win-amd64-3.8\matplotlib
  copying lib\matplotlib\animation.py -> build\lib.win-amd64-3.8\matplotlib
  copying lib\matplotlib\artist.py -> build\lib.win-amd64-3.8\matplotlib
  copying lib\matplotlib\axis.py -> build\lib.win-amd64-3.8\matplotlib
  copying lib\matplotlib\backend_bases.py -> build\lib.win-amd64-3.8\matplotlib
  copying lib\matplotlib\backend_managers.py -> build\lib.win-amd64-3.8\matplotlib
  copying lib\matplotlib\backend_tools.py -> build\lib.win-amd64-3.8\matplotlib
  copying lib\matplotlib\bezier.py -> build\lib.win-amd64-3.8\matplotlib
  copying lib\matplotlib\blocking_input.py -> build\lib.win-amd64-3.8\matplotlib
  copying lib\matplotlib\category.py -> build\lib.win-amd64-3.8\matplotlib
  copying lib\matplotlib\cm.py ->

  copying lib\matplotlib\cbook\__init__.py -> build\lib.win-amd64-3.8\matplotlib\cbook
  creating build\lib.win-amd64-3.8\matplotlib\compat
  copying lib\matplotlib\compat\subprocess.py -> build\lib.win-amd64-3.8\matplotlib\compat
  copying lib\matplotlib\compat\__init__.py -> build\lib.win-amd64-3.8\matplotlib\compat
  creating build\lib.win-amd64-3.8\matplotlib\projections
  copying lib\matplotlib\projections\geo.py -> build\lib.win-amd64-3.8\matplotlib\projections
  copying lib\matplotlib\projections\polar.py -> build\lib.win-amd64-3.8\matplotlib\projections
  copying lib\matplotlib\projections\__init__.py -> build\lib.win-amd64-3.8\matplotlib\projections
  creating build\lib.win-amd64-3.8\matplotlib\sphinxext
  copying lib\matplotlib\sphinxext\mathmpl.py -> build\lib.win-amd64-3.8\matplotlib\sphinxext
  copying lib\matplotlib\sphinxext\plot_directive.py -> build\lib.win-amd64-3.8\matplotlib\sphinxext
  copying lib\matplotlib\sphinxext\__init__.py -> build\lib.win-amd64-3.8\matplotl

    customize IntelItaniumVisualFCompiler
    Could not locate executable efl
    customize Gnu95FCompiler
    Could not locate executable gfortran
    Could not locate executable f95
    customize G95FCompiler
    Could not locate executable g95
    customize IntelEM64VisualFCompiler
    customize IntelEM64TFCompiler
    Could not locate executable efort
    Could not locate executable efc
    customize PGroupFlangCompiler
    Could not locate executable flang
    don't know how to compile Fortran code on platform 'nt'
      NOT AVAILABLE
    
    atlas_3_10_blas_threads_info:
    Setting PTATLAS=ATLAS
    No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
    customize MSVCCompiler
      libraries tatlas not found in ['C:\\Users\\USER\\anaconda3\\lib', 'C:\\', 'C:\\Users\\USER\\anaconda3\\libs']
      NOT AVAILABLE
    
    atlas_3_10_blas_info:
    No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
    cus

In [5]:
np.__version__

'1.19.2'

## ndarray dtype

In [6]:
a = np.array([1, 2, 3])
a

array([1, 2, 3])

In [14]:
type(a)

numpy.ndarray

In [15]:
# indexing이 list와 방식이 같음
a[0]

1

In [7]:
a.

SyntaxError: invalid syntax (<ipython-input-7-b4ce96ddcee0>, line 1)

- append() 같은 함수가 없음 -> 즉, python의 list와는 다른 data type임

## Universal function

In [8]:
a = [1, 2, 3]
b = [4, 5, 6]

new_list = []
for e1, e2 in zip(a, b):
    new_list.append(e1 + e2)
new_list

[5, 7, 9]

In [9]:
a + b

[1, 2, 3, 4, 5, 6]

In [10]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

In [11]:
# 길이가 길어도 근사적으로 1초가 걸린다
a + b

array([5, 7, 9])

In [12]:
# np.sum
# np.abs
# np.log
# np.exp
# np.isnan
# ...

- n차원 array

In [13]:
a = np.array([  [1, 2],  [3, 4]   ])
a

array([[1, 2],
       [3, 4]])

In [14]:
# readability 높이기
a = np.array(
    [
        [1, 2],
        [3, 4],
    ]
)

In [15]:
a[0][1]

2

In [16]:
a + a

array([[2, 4],
       [6, 8]])